Repository halo-dev/plugin-s3, pull requests merged in 2023-09, with the labels that each got.

#59 feat: Associate files originally in s3
  build.gradle
  console/.editorconfig
  console/.eslintrc.cjs
  console/.gitignore
  console/env.d.ts
  console/package.json
  console/pnpm-lock.yaml
  console/src/assets/logo.svg
  console/src/controller/index.ts
  console/src/controller/s-3-link-controller/getApisS3OsHaloRunV1Alpha1ObjectsByPolicyName.ts
  console/src/controller/s-3-link-controller/getApisS3OsHaloRunV1Alpha1PoliciesS3.ts
  console/src/controller/s-3-link-controller/index.ts
  console/src/controller/s-3-link-controller/postApisS3OsHaloRunV1Alpha1AttachmentsLink.ts
  console/src/index.ts
  console/src/interface/apiTypes/LinkRequest.ts
  console/src/interface/apiTypes/LinkResult.ts
  console/src/interface/apiTypes/LinkResultItem.ts
  console/src/interface/apiTypes/Metadata.ts
  console/src/interface/apiTypes/ObjectVo.ts
  console/src/interface/apiTypes/Policy.ts
  console/src/interface/apiTypes/PolicySpec.ts
  console/src/interface/apiTypes/S3ListResult.ts
  console/src/interface/index.ts
  console/src/swagger.config.json
  console/src/utils/request.ts
  console/src/views/HomeView.vue
  console/tsconfig.app.json
  console/tsconfig.config.json
  console/tsconfig.json
  console/tsconfig.vitest.json
  console/vite.config.ts
  gradle.properties
  src/main/java/run/halo/s3os/FileNameUtils.java
  src/main/java/run/halo/s3os/LinkRequest.java
  src/main/java/run/halo/s3os/LinkResult.java
  src/main/java/run/halo/s3os/S3LinkController.java
  src/main/java/run/halo/s3os/S3LinkService.java
  src/main/java/run/halo/s3os/S3LinkServiceImpl.java
  src/main/java/run/halo/s3os/S3ListResult.java
  src/main/java/run/halo/s3os/S3OsAttachmentHandler.java
  src/main/resources/console/main.js
  src/main/resources/extensions/settings.yaml
  src/main/resources/plugin.yaml
Labels: lgtm, approved, release-note

#71 chore: Optimize access_key description
  src/main/resources/extensions/policy-template-s3os.yaml
Labels: lgtm, approved, release-note

#72 chore: Unify the author information of plugin.yaml
  src/main/java/run/halo/s3os/S3LinkServiceImpl.java
  src/main/resources/plugin.yaml
Labels: release-note-none, lgtm, approved

#73 chore: change repo organization to halo-dev
  README.md
  src/main/resources/plugin.yaml
Labels: release-note-none, lgtm, kind/cleanup, approved

#76 chore: correct typos
  src/main/resources/extensions/policy-template-s3os.yaml
Labels: release-note-none, lgtm, approved

#74 feat: Time placeholder of upload path
  src/main/java/run/halo/s3os/FilePathUtils.java
  src/main/java/run/halo/s3os/S3LinkServiceImpl.java
  src/main/java/run/halo/s3os/S3OsProperties.java
  src/main/resources/extensions/policy-template-s3os.yaml
Labels: lgtm, approved, release-note

#78 chore: Modify upyun compatibility and service provider document hyperlink format
  README.md
Labels: release-note-none, lgtm, approved
