Repository halo-dev/plugin-s3, pull requests merged in 2023-10, with the labels that each got.

#80 Exclude reactive-streams module for runtime classpath
  build.gradle
Labels: kind/bug, lgtm, approved, release-note

#81 Remove unused dependencies
  build.gradle
Labels: release-note-none, lgtm, approved

#83 fix: remove v-permission to avoid checkbox disappearing
  console/src/views/HomeView.vue
Labels: release-note-none, lgtm, approved

#84 chore: update github action
  .github/workflows/workflow.yaml
  build.gradle
Labels: release-note-none, lgtm, approved, kind/improvement

#87 feat: improve the styles of the data list filter area on the mobile devices
  console/src/views/HomeView.vue
  src/main/resources/console/main.js
Labels: lgtm, approved, release-note

#79 feat: add URL suffix to files of specified type
  src/main/java/run/halo/s3os/S3OsAttachmentHandler.java
  src/main/java/run/halo/s3os/S3OsProperties.java
  src/main/java/run/halo/s3os/UrlUtils.java
  src/main/resources/extensions/policy-template-s3os.yaml
  src/test/java/run/halo/s3os/UrlUtilsTest.java
Labels: kind/feature, lgtm, approved, release-note

#89 perf: improve s3link role permissions
  build.gradle
  console/src/index.ts
  console/src/views/S3Link.vue
  src/main/resources/console/main.js
  src/main/resources/extensions/s3os-role-template.yaml
Labels: lgtm, approved, release-note

#91 fix: s3 link error when filename renaming enable
  src/main/java/run/halo/s3os/S3LinkServiceImpl.java
  src/main/java/run/halo/s3os/S3OsAttachmentHandler.java
Labels: lgtm, approved, release-note

#94 Fix findUrlSuffix NPE when upgrading from old version
  src/main/java/run/halo/s3os/UrlUtils.java
  src/test/java/run/halo/s3os/UrlUtilsTest.java
Labels: kind/bug, lgtm, approved, release-note

#95 chore: update .gitignore and remove untracked directories
  .gitignore
  src/main/resources/console/main.js
Labels: release-note-none, lgtm, approved
