Repository halo-dev/plugin-s3, pull requests merged in 2023-08, with the labels that each got.

#57 Fallback to default handler for backward compatibility
  src/main/java/run/halo/s3os/S3OsAttachmentHandler.java
Labels: lgtm, approved, release-note, kind/improvement

#61 docs: update usage documentation of readme file
  README.md
Labels: release-note-none, lgtm, approved, kind/documentation

#60 feat: automatic random file renaming optional feature
  src/main/java/run/halo/s3os/FileNameUtils.java
  src/main/java/run/halo/s3os/S3OsAttachmentHandler.java
  src/main/java/run/halo/s3os/S3OsProperties.java
  src/main/resources/extensions/policy-template-s3os.yaml
Labels: lgtm, approved, release-note
