Repository halo-dev/plugin-s3, pull requests merged in 2024-02, with the labels that each got.

#116 refactor: place the entry for the S3 link page in the side menu
  console/package.json
  console/pnpm-lock.yaml
  console/src/index.ts
  src/main/resources/plugin.yaml
Labels: lgtm, approved, release-note, kind/improvement

#117 chore: simplify bundler config
  build.gradle
  console/package.json
  console/pnpm-lock.yaml
  console/vite.config.ts
Labels: release-note-none, lgtm, approved, kind/improvement

#119 fix: missing page size selector style
  console/src/views/S3Link.vue
Labels: lgtm, approved, release-note

#120 chore: updated s3 link entrance description
  README.md
Labels: release-note-none, lgtm, approved

#121 chore: remove plugin view permissions from S3 Link permission dependency
  src/main/resources/extensions/s3os-role-template.yaml
Labels: release-note-none, lgtm, approved

#115 feat: add support for custom template in automatic renaming during upload
  README.md
  build.gradle
  src/main/java/run/halo/s3os/FileNameUtils.java
  src/main/java/run/halo/s3os/FilePathUtils.java
  src/main/java/run/halo/s3os/PlaceholderReplacer.java
  src/main/java/run/halo/s3os/S3OsAttachmentHandler.java
  src/main/java/run/halo/s3os/S3OsProperties.java
  src/main/resources/extensions/policy-template-s3os.yaml
  src/test/java/run/halo/s3os/FileNameUtilsTest.java
  src/test/java/run/halo/s3os/PlaceholderReplacerTest.java
Labels: lgtm, approved, release-note
