Repository halo-dev/plugin-s3, pull requests merged in 2024-03, with the labels that each got.

#123 chore: bump version to 1.8.0
  gradle.properties
Labels: release-note-none, lgtm, approved

#124 chore: correcting incorrect policy template field help text
  src/main/resources/extensions/policy-template-s3os.yaml
Labels: release-note-none, lgtm, approved

#126 fix: Correct the formatting of Milliseconds to be a 3-digit number
  src/main/java/run/halo/s3os/PlaceholderReplacer.java
Labels: lgtm, approved, release-note

#128 chore: rename displayName to S3 对象存储
  src/main/resources/extensions/policy-template-s3os.yaml
Labels: lgtm, approved, release-note, kind/improvement

#130 Simplify GitHub workflow by using reusable workflow
  .github/workflows/cd.yaml
  .github/workflows/ci.yaml
  .github/workflows/workflow.yaml
  build.gradle
Labels: release-note-none, lgtm, kind/cleanup, approved
